# Flutter project placeholder (initialize with `flutter create` later)
name: lost_found_mobile
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.5.0
  provider: ^6.1.1
  intl: any
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.5
  path_provider: ^2.1.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  uuid: ^4.5.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  web_socket_channel: ^3.0.1
  connectivity_plus: ^6.1.0
  crypto: ^3.0.3 # For password encryption and hashing
  http: ^1.2.0 # For API calls
  geolocator: ^10.1.0 # For geolocation and distance calculation
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mocktail: ^1.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: AppFont
  #     fonts:
  #       - asset: assets/fonts/placeholder.ttf
