# Flutter project placeholder (initialize with `flutter create` later)
name: lost_found_mobile
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  flutter_riverpod: ^2.4.9
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get_it: ^7.6.7
  go_router: ^14.2.7
  http: ^1.1.0
  image: ^4.1.7
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
