"""Add new report fields for frontend integration

Revision ID: bd48418a6fd3
Revises: db38502b56d8
Create Date: 2025-10-19 18:12:10.796183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd48418a6fd3'
down_revision: Union[str, None] = 'db38502b56d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.add_column('reports', sa.Column('occurred_time', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('contact_info', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('additional_info', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('safety_status', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('is_safe', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('is_urgent', sa.Boolean(), nullable=True))
    op.add_column('reports', sa.Column('reward_amount', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('moderation_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'moderation_notes')
    op.drop_column('reports', 'reward_amount')
    op.drop_column('reports', 'is_urgent')
    op.drop_column('reports', 'is_safe')
    op.drop_column('reports', 'safety_status')
    op.drop_column('reports', 'condition')
    op.drop_column('reports', 'additional_info')
    op.drop_column('reports', 'contact_info')
    op.drop_column('reports', 'longitude')
    op.drop_column('reports', 'latitude')
    op.drop_column('reports', 'occurred_time')
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    # ### end Alembic commands ###
