name: API Smoke Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    smoke:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgis/postgis:15-3.3
                env:
                    POSTGRES_DB: lostfound
                    POSTGRES_USER: lostfound
                    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                ports: ["5432:5432"]
                options: >-
                    --health-cmd "pg_isready -U lostfound" 
                    --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis:7-alpine
                ports: ["6379:6379"]
                options: >-
                    --health-cmd "redis-cli ping" 
                    --health-interval 10s --health-timeout 5s --health-retries 5
        env:
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            REDIS_URL: redis://localhost:6379/0
            JWT_SECRET: test_jwt_secret_please_replace
            ADMIN_EMAIL: admin@example.com
            ADMIN_PASSWORD: password123
            CORS_ORIGINS: http://localhost:3000
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Compose database URL
              run: |
                  : "Set default password if secret missing"
                  if [ -z "${POSTGRES_PASSWORD}" ]; then POSTGRES_PASSWORD=lostfound; fi
                  echo "DATABASE_URL=postgresql://lostfound:${POSTGRES_PASSWORD}@localhost:5432/lostfound" >> $GITHUB_ENV

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"
                  cache-dependency-path: backend/api/requirements.txt

            - name: Install API dependencies
              working-directory: backend/api
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run migrations
              working-directory: backend/api
              run: alembic upgrade head

            - name: Seed data (push only)
              if: ${{ github.event_name == 'push' }}
              working-directory: backend/api
              run: python scripts/seed_minimal_data.py

            - name: Start API (background)
              working-directory: backend/api
              run: |
                  nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
                  sleep 5

            - name: Wait for readiness
              run: |
                  for i in {1..30}; do
                    curl -sf http://localhost:8000/readyz && break || sleep 1; done
                  curl -s http://localhost:8000/healthz

            - name: Install jq
              run: sudo apt-get update && sudo apt-get install -y jq

            - name: Run smoke test
              working-directory: backend/api
              run: |
                  if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then \
                     python ../../scripts/smoke_test_api.py --no-create; \
                  else \
                     python ../../scripts/smoke_test_api.py; \
                  fi
